### ISSUE TITLE
Error When Installing

### ISSUE THREAD

**Issue by SportsAnnouncing** [JoshuaCarroll/BasketballRosterManager#35]
System Update Required

Unable to install or run the application.  The application requires that assembly System.Data.SqlServerCe Version 4.0.0.0 be installed in the Global Assembly Cache (GAC) first.

More information on this system update can be found by visiting the site here.

And I get this link:  http://www.decodethecode.com/

**Comment by JoshuaCarroll** [comment]
I have published version 1.8.1.1.  Please see if this will fix the issue.  You should be able to just open the application.  It will automatically check for an update, just be sure to accept the update.  Please update this issue with the results.

**Comment by JoshuaCarroll** [comment]
OP reported that the application updated successfully, but returned a new error:

> The following error occured creating the database:
> 
> Unable to load the native components of SQL Server Compact corresponding to the ADO.NET 
> provider of version 8876. Install the correct version of SQL Server Compact. Refer to KB article 
> 974247 for more details.

The OP is using Windows 7.

**Comment by JoshuaCarroll** [comment]
Commit d9fd9c1 has been compiled and published as v1.8.1.2.  Please update and report the results.

**Comment by JoshuaCarroll** [comment]
OP now has new error message:

> The follow [sic] error occured [sic] creating the database:
> is not a valid Win32 application.  (Exception from HRESULT: 0x800700C1)

**Comment by JoshuaCarroll** [comment]
Commit e288681 has been compiled and published as v1.8.1.3. This update will *not* fix the latest problem. It will, however, give you the option to create an error report. The program will be able to tell me exactly where the problem is. Please recreate the error and send the error report when prompted. Note that you *will* have an opportunity to review the error report before you submit it.

**Comment by JoshuaCarroll** [comment]
I think the OP might have used the "launch" option on the deployment page without having all the components installed.  I advised him to remove and perform a full install.

**Comment by JoshuaCarroll** [comment]
As previously noted, I think the OP might have used the "launch" option on the deployment page without having all the components installed. I advised him to remove and perform a full install.  If I learn otherwise, I will re-open this issue.
