### ISSUE TITLE
When Opening The Program

### ISSUE THREAD

**Issue by SportsAnnouncing** [JoshuaCarroll/BasketballRosterManager#38]
ERROR

The following error occured creating the database:

Unable to load the native components of SQL Server Compact corresponding to the ADO.NET provider of version 8876.  Install the correct version of SQL Server Compact. Refer to KB article 974247 for more details.

**Comment by JoshuaCarroll** [comment]
User is using Windows 7.

This issue arose after the changes supporting issue #35.

**Comment by JoshuaCarroll** [comment]
I think there may be another way to address issue #35 without causing this problem.  In either case, since these are definitely related, I'm going to copy the pertinent details into that issue and close this one.
