### ISSUE TITLE
Error while creating database

### ISSUE THREAD

**Issue by SportsAnnouncing** [JoshuaCarroll/BasketballRosterManager#40]
An error occurred while the program attempted to create the database.
### Message
>  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

### Help link
> 

### Source
> mscorlib

### Stack trace
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
>    at System.Data.SqlServerCe.UnmanagedLibraryHelper..ctor(String fileName)
>    at System.Data.SqlServerCe.NativeMethodsHelper..ctor(String modulePath)
>    at System.Data.SqlServerCe.NativeMethods.LoadValidLibrary(String modulePath)
>    at System.Data.SqlServerCe.NativeMethods.LoadNativeBinariesFromPrivateFolder(String privateInstall)
>    at System.Data.SqlServerCe.NativeMethods.LoadNativeBinaries()
>    at System.Data.SqlServerCe.SqlCeEngine..ctor()
>    at System.Data.SqlServerCe.SqlCeEngine..ctor(String connectionString)
>    at Basketball_Roster_Manager.Form1.verifyDataPath()

**Comment by JoshuaCarroll** [comment]
This is directly related to #35.

**Comment by SportsAnnouncing** [comment]
Newest issue:

PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.34209
	System.Deployment.dll 		: 4.0.30319.34280 built by: FX452RTMGDR
	clr.dll 			: 4.0.30319.34209 built by: FX452RTMGDR
	dfdll.dll 			: 4.0.30319.34280 built by: FX452RTMGDR
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: file:///C:/Users/Jarrod%20Wronski/Desktop/Basketball%20Roster%20Manager.appref-ms%7C
						Server		: Microsoft-IIS/7.5
						X-Powered-By	: ASP.NET
	Deployment Provider url		: http://www.decodethecode.com/basketball_roster_manager/Basketball%20Roster%20Manager.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Jarrod Wronski\Desktop\Basketball Roster Manager.appref-ms| resulted in exception. Following failure messages were detected:
		+ The deployment identity does not match the subscription.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [12/15/2015 12:31:18 AM] : Activation of C:\Users\Jarrod Wronski\Desktop\Basketball Roster Manager.appref-ms| has started.
	* [12/15/2015 12:31:19 AM] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
	Following errors were detected during this operation.
	* [12/15/2015 12:31:19 AM] System.Deployment.Application.DeploymentException (SubscriptionState)
		- The deployment identity does not match the subscription.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SubscriptionStore.CheckUpdateInManifest(SubscriptionState subState, Uri updateCodebaseUri, AssemblyManifest deployment, Version currentVersion, Boolean& bUpdateInPKTGroup)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentUpdate(SubscriptionState& subState, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by JoshuaCarroll** [comment]
Further details available in issue #35.
